export const SalesDashboard = {
  name: 'sales_dashboard',
  label: 'Sales Performance',
  description: 'Pipeline analytics, win rate trends, and rep performance',
  columns: 12,
  gap: 4,
  refreshInterval: 180,
  widgets: [
    // ─── Row 1: Pipeline KPIs ─────────────────────────────────────────
    {
      id: 'total_pipeline_value',
      title: 'Total Pipeline',
      type: 'metric' as const,
      object: 'opportunity',
      valueField: 'amount',
      aggregate: 'sum' as const,
      colorVariant: 'blue' as const,
      layout: { x: 0, y: 0, w: 3, h: 2 },
      options: {
        icon: 'DollarSign',
        format: '$0,0',
        trend: { value: 8.4, direction: 'up' as const, label: 'vs last quarter' },
      },
    },
    {
      id: 'closed_won_qtd',
      title: 'Closed Won (QTD)',
      type: 'metric' as const,
      object: 'opportunity',
      filter: { stage: 'closed_won' },
      valueField: 'amount',
      aggregate: 'sum' as const,
      colorVariant: 'success' as const,
      layout: { x: 3, y: 0, w: 3, h: 2 },
      options: {
        icon: 'Trophy',
        format: '$0,0',
        trend: { value: 14.7, direction: 'up' as const, label: 'vs last quarter' },
      },
    },
    {
      id: 'open_opportunities',
      title: 'Open Opportunities',
      type: 'metric' as const,
      object: 'opportunity',
      filter: { stage: { $nin: ['closed_won', 'closed_lost'] } },
      aggregate: 'count' as const,
      colorVariant: 'orange' as const,
      layout: { x: 6, y: 0, w: 3, h: 2 },
      options: {
        icon: 'Briefcase',
        trend: { value: 2.1, direction: 'down' as const, label: 'vs last quarter' },
      },
    },
    {
      id: 'avg_deal_size',
      title: 'Avg Deal Size',
      type: 'metric' as const,
      object: 'opportunity',
      filter: { stage: 'closed_won' },
      valueField: 'amount',
      aggregate: 'avg' as const,
      colorVariant: 'purple' as const,
      layout: { x: 9, y: 0, w: 3, h: 2 },
      options: {
        icon: 'BarChart3',
        format: '$0,0',
        trend: { value: 4.3, direction: 'up' as const, label: 'vs last quarter' },
      },
    },

    // ─── Row 2: Pipeline & Trends ─────────────────────────────────────
    {
      id: 'pipeline_by_stage',
      title: 'Pipeline by Stage',
      type: 'bar' as const,
      object: 'opportunity',
      categoryField: 'stage',
      valueField: 'amount',
      aggregate: 'sum' as const,
      layout: { x: 0, y: 2, w: 6, h: 4 },
      options: {
        xField: 'stage',
        yField: 'amount',
        data: {
          provider: 'object' as const,
          object: 'opportunity',
          aggregate: { field: 'amount', function: 'sum' as const, groupBy: 'stage' },
        },
      },
    },
    {
      id: 'monthly_revenue_trend',
      title: 'Monthly Revenue Trend',
      type: 'area' as const,
      object: 'opportunity',
      filter: { stage: 'closed_won' },
      categoryField: 'close_date',
      valueField: 'amount',
      aggregate: 'sum' as const,
      layout: { x: 6, y: 2, w: 6, h: 4 },
      options: {
        xField: 'close_date',
        yField: 'amount',
        data: {
          provider: 'object' as const,
          object: 'opportunity',
          filter: { stage: 'closed_won' },
          aggregate: { field: 'amount', function: 'sum' as const, groupBy: 'close_date' },
        },
      },
    },

    // ─── Row 3: Performance Breakdown ─────────────────────────────────
    {
      id: 'opportunities_by_owner',
      title: 'Opportunities by Owner',
      type: 'bar' as const,
      object: 'opportunity',
      categoryField: 'owner',
      valueField: 'amount',
      aggregate: 'sum' as const,
      layout: { x: 0, y: 6, w: 6, h: 4 },
      options: {
        xField: 'owner',
        yField: 'amount',
        data: {
          provider: 'object' as const,
          object: 'opportunity',
          aggregate: { field: 'amount', function: 'sum' as const, groupBy: 'owner' },
        },
      },
    },
    {
      id: 'lead_source_breakdown',
      title: 'Lead Source',
      type: 'donut' as const,
      object: 'opportunity',
      categoryField: 'lead_source',
      valueField: 'amount',
      aggregate: 'sum' as const,
      layout: { x: 6, y: 6, w: 6, h: 4 },
      options: {
        xField: 'lead_source',
        yField: 'amount',
        data: {
          provider: 'object' as const,
          object: 'opportunity',
          aggregate: { field: 'amount', function: 'sum' as const, groupBy: 'lead_source' },
        },
      },
    },

    // ─── Row 4: Top Deals ─────────────────────────────────────────────
    {
      id: 'top_opportunities',
      title: 'Top Open Opportunities',
      type: 'table' as const,
      object: 'opportunity',
      layout: { x: 0, y: 10, w: 12, h: 4 },
      options: {
        columns: [
          { header: 'Opportunity', accessorKey: 'name' },
          { header: 'Account', accessorKey: 'account' },
          { header: 'Amount', accessorKey: 'amount' },
          { header: 'Stage', accessorKey: 'stage' },
          { header: 'Close Date', accessorKey: 'close_date' },
        ],
        sortBy: 'amount',
        sortOrder: 'desc',
        limit: 10,
        data: {
          provider: 'object' as const,
          object: 'opportunity',
          filter: { stage: { $nin: ['closed_won', 'closed_lost'] } },
        },
      },
    },
  ],
};
