export const ServiceDashboard = {
  name: 'service_dashboard',
  label: 'Customer Service',
  description: 'Case load, SLA health, and resolution performance',
  columns: 12,
  gap: 4,
  refreshInterval: 60,
  widgets: [
    // ─── Row 1: Case-Load KPIs ────────────────────────────────────────
    {
      id: 'open_cases',
      title: 'Open Cases',
      type: 'metric' as const,
      object: 'case',
      filter: { is_closed: false },
      aggregate: 'count' as const,
      colorVariant: 'orange' as const,
      layout: { x: 0, y: 0, w: 3, h: 2 },
      options: {
        icon: 'Inbox',
        trend: { value: 6.2, direction: 'down' as const, label: 'vs last week' },
      },
    },
    {
      id: 'critical_cases',
      title: 'Critical Cases',
      type: 'metric' as const,
      object: 'case',
      filter: { priority: 'critical', is_closed: false },
      aggregate: 'count' as const,
      colorVariant: 'danger' as const,
      layout: { x: 3, y: 0, w: 3, h: 2 },
      options: {
        icon: 'AlertTriangle',
        trend: { value: 1.0, direction: 'up' as const, label: 'vs last week' },
      },
    },
    {
      id: 'avg_resolution_time',
      title: 'Avg Resolution Time',
      type: 'metric' as const,
      object: 'case',
      filter: { is_closed: true },
      valueField: 'resolution_time_hours',
      aggregate: 'avg' as const,
      colorVariant: 'blue' as const,
      layout: { x: 6, y: 0, w: 3, h: 2 },
      options: {
        icon: 'Clock',
        trend: { value: 9.8, direction: 'down' as const, label: 'vs last week' },
      },
    },
    {
      id: 'sla_violations',
      title: 'SLA Violations',
      type: 'metric' as const,
      object: 'case',
      filter: { is_sla_violated: true },
      aggregate: 'count' as const,
      colorVariant: 'warning' as const,
      layout: { x: 9, y: 0, w: 3, h: 2 },
      options: {
        icon: 'ShieldAlert',
        trend: { value: 2.4, direction: 'down' as const, label: 'vs last week' },
      },
    },

    // ─── Row 2: Distribution ──────────────────────────────────────────
    {
      id: 'cases_by_status',
      title: 'Cases by Status',
      type: 'donut' as const,
      object: 'case',
      filter: { is_closed: false },
      categoryField: 'status',
      aggregate: 'count' as const,
      layout: { x: 0, y: 2, w: 4, h: 4 },
      options: {
        xField: 'status',
        yField: 'count',
        data: {
          provider: 'object' as const,
          object: 'case',
          filter: { is_closed: false },
          aggregate: { field: 'count', function: 'count' as const, groupBy: 'status' },
        },
      },
    },
    {
      id: 'cases_by_priority',
      title: 'Cases by Priority',
      type: 'pie' as const,
      object: 'case',
      filter: { is_closed: false },
      categoryField: 'priority',
      aggregate: 'count' as const,
      layout: { x: 4, y: 2, w: 4, h: 4 },
      options: {
        xField: 'priority',
        yField: 'count',
        data: {
          provider: 'object' as const,
          object: 'case',
          filter: { is_closed: false },
          aggregate: { field: 'count', function: 'count' as const, groupBy: 'priority' },
        },
      },
    },
    {
      id: 'cases_by_origin',
      title: 'Cases by Origin',
      type: 'bar' as const,
      object: 'case',
      categoryField: 'origin',
      aggregate: 'count' as const,
      layout: { x: 8, y: 2, w: 4, h: 4 },
      options: {
        xField: 'origin',
        yField: 'count',
        data: {
          provider: 'object' as const,
          object: 'case',
          aggregate: { field: 'count', function: 'count' as const, groupBy: 'origin' },
        },
      },
    },

    // ─── Row 3: Volume Trend ──────────────────────────────────────────
    {
      id: 'daily_case_volume',
      title: 'Daily Case Volume',
      type: 'area' as const,
      object: 'case',
      categoryField: 'created_date',
      aggregate: 'count' as const,
      layout: { x: 0, y: 6, w: 8, h: 4 },
      options: {
        xField: 'created_date',
        yField: 'count',
        data: {
          provider: 'object' as const,
          object: 'case',
          aggregate: { field: 'count', function: 'count' as const, groupBy: 'created_date' },
        },
      },
    },
    {
      id: 'sla_compliance',
      title: 'SLA Compliance',
      type: 'metric' as const,
      object: 'case',
      filter: { is_closed: true },
      aggregate: 'count' as const,
      colorVariant: 'success' as const,
      layout: { x: 8, y: 6, w: 4, h: 4 },
      options: {
        icon: 'ShieldCheck',
        description: 'Cases resolved within SLA',
        trend: { value: 3.1, direction: 'up' as const, label: 'vs last period' },
      },
    },

    // ─── Row 4: My Open Cases ─────────────────────────────────────────
    {
      id: 'my_open_cases',
      title: 'My Open Cases',
      type: 'table' as const,
      object: 'case',
      filter: { is_closed: false },
      layout: { x: 0, y: 10, w: 12, h: 4 },
      options: {
        columns: [
          { header: 'Subject', accessorKey: 'subject' },
          { header: 'Account', accessorKey: 'account' },
          { header: 'Priority', accessorKey: 'priority' },
          { header: 'Status', accessorKey: 'status' },
          { header: 'Created', accessorKey: 'created_date' },
        ],
        sortBy: 'priority',
        sortOrder: 'desc',
        limit: 10,
        data: {
          provider: 'object' as const,
          object: 'case',
          filter: { is_closed: false },
        },
      },
    },
  ],
};
