export { ObjectView } from './ObjectView';
export { RecordDetailView } from './RecordDetailView';
export { RecordFormPage } from './RecordFormPage';
export type { RecordFormPageProps } from './RecordFormPage';
export { DashboardView } from './DashboardView';
export { PageView } from './PageView';
export { ReportView } from './ReportView';
export { SearchResultsPage } from './SearchResultsPage';
export { ActionConfirmDialog } from './ActionConfirmDialog';
export { ActionParamDialog } from './ActionParamDialog';
export { ActionResultDialog, type ResultDialogState } from './ActionResultDialog';
export { MetadataToggle, MetadataPanel } from './MetadataInspector';
export { ViewConfigPanel } from './ViewConfigPanel';
export { CreateViewDialog } from './CreateViewDialog';
export { DeclaredActionsBar, type DeclaredActionsBarProps } from './DeclaredActionsBar';
