import React from 'react';
import { EmptyValue } from '@object-ui/components';
import { FieldWidgetComponentProps } from './types.js';

/**
 * AutoNumberField - Read-only auto-generated field
 * Values are automatically generated by the system and cannot be edited
 */
export function AutoNumberField({ value, field, ...props }: FieldWidgetComponentProps<string | number>) {
  if (value == null) {
    return <EmptyValue className={props.className} />;
  }
  return (
    <span className={`text-sm font-mono text-gray-700 ${props.className || ''}`}>
      {String(value)}
    </span>
  );
}
