/**
 * ObjectUI
 * Copyright (c) 2024-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * `ObjectSchemaMetadata` ↔ `@objectstack/spec` derivation guard (objectui#5362).
 *
 * The maintainer ruled (2026-08-20, on #5362) that the object document type
 * belongs to `@objectstack/spec` and objectui DERIVES it rather than keeping a
 * hand-written second declaration. The hand-written interface this replaced
 * declared none of `titleFormat` / `listViews` / `icon` — three keys the
 * shipped runtime reads — while declaring nine members nothing reads and the
 * spec does not know. This guard is the forcing function that keeps the
 * settlement settled:
 *
 *   1. The derivation is structural — `ObjectSchemaMetadata` is the spec's
 *      `ServiceObject` plus the measured client delta, nothing else. Reverting
 *      the alias to a hand-written interface fails the `Equal` assertion and
 *      the three-key fixture below.
 *   2. The three read-but-formerly-undeclared keys are admitted, at compile
 *      time (typed fixture) and at runtime (spec zod shape).
 *   3. The SPELLING is settled: camelCase `listViews` is declared; snake
 *      `list_views` is not a key of the document type or the spec schema.
 *      The runtime keeps a snake READ fallback for stored app data published
 *      before this settlement (never censused — objectstack#7917); that
 *      tolerance lives at the read sites and must NOT leak back into the
 *      declared type, which is what the `@ts-expect-error` below pins.
 *   4. The client-extension surface stays measured: every member must have a
 *      live runtime read. Growing `ObjectSchemaClientExtensions` fails the
 *      key-set assertion, forcing the promote-upstream / justify-here
 *      decision consciously (same forcing function as
 *      `object-view-spec-parity.test.ts`).
 *
 * When one of these fails, do NOT edit this file first. Decide whether the
 * key belongs upstream in `@objectstack/spec` (promote it — the #5362 route
 * for the three keys was exactly that, objectstack#10144) or is a genuine
 * objectui-only runtime read (add it to the extension with its read site).
 */
import { describe, it, expect } from 'vitest';
import { ObjectSchema as SpecObjectSchema } from '@objectstack/spec/data';
import type { ServiceObject } from '@objectstack/spec/data';
import type {
  ObjectSchemaMetadata,
  ObjectSchemaClientExtensions,
} from '../field-types.js';

// ── compile-time half ────────────────────────────────────────────────────────
// Compiled by `tsconfig.test.json` via this package's `type-check` script —
// see that file's header for why tests must be in a compiled project at all
// (objectstack#4074: `satisfies` contracts that no tsc invocation ever read).

type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B
  ? 1
  : 2
  ? true
  : false;
type Assert<T extends true> = T;

// 1. Structural derivation — the alias IS spec type + client delta.
type _derivation = Assert<
  Equal<ObjectSchemaMetadata, ServiceObject & ObjectSchemaClientExtensions>
>;

// 4. The client delta stays exactly the measured set. `editMode` is read by
// `@object-ui/app-shell` (`utils/recordFormNavigation.ts`, routed by
// `AppContent`'s central `handleEdit` dispatcher).
type _extensionSurface = Assert<
  Equal<keyof ObjectSchemaClientExtensions, 'editMode'>
>;

// 2. The three keys #5362 measured as read-but-undeclared are admitted, and
// a typed document can carry the client extension alongside them.
const derivedAdmitsTheThreeKeys: ObjectSchemaMetadata = {
  name: 'task',
  fields: {
    subject: { type: 'text', label: 'Subject', required: true },
  },
  icon: 'check-square',
  titleFormat: '${subject}',
  listViews: {
    all: { label: 'All Tasks', columns: ['subject'] },
  },
  editMode: 'page',
};

// 3. Snake `list_views` is NOT part of the declared surface. If this
// directive ever reports as unused, the snake spelling has leaked back into
// the type — that is a regression of the #5362 settlement, not a cleanup.
const snakeSpellingIsNotDeclared: ObjectSchemaMetadata = {
  name: 'task',
  fields: {},
  // @ts-expect-error -- `list_views` was never a spec key; the spec declares only camelCase `listViews` (#5362).
  list_views: {},
};

// ── runtime half ─────────────────────────────────────────────────────────────

/** Top-level keys of a zod object (same helper as the sibling parity guards). */
function shapeKeys(schema: unknown): string[] {
  const carrier = schema as { shape?: unknown; _def?: { shape?: unknown } };
  const shape = carrier?.shape ?? carrier?._def?.shape;
  const resolved = typeof shape === 'function' ? (shape as () => object)() : shape;
  return resolved && typeof resolved === 'object' ? Object.keys(resolved) : [];
}

describe('ObjectSchemaMetadata spec derivation (#5362)', () => {
  const keys = shapeKeys(SpecObjectSchema);

  it('reads a live spec shape (positive control for every absence below)', () => {
    // A broken import or an empty shape would make every `not.toContain`
    // below pass vacuously; pin the corpus first.
    expect(keys.length).toBeGreaterThan(30);
    expect(keys).toContain('name');
    expect(keys).toContain('fields');
  });

  it('declares the three keys the runtime reads: icon, titleFormat, listViews', () => {
    expect(keys).toContain('icon');
    expect(keys).toContain('titleFormat');
    expect(keys).toContain('listViews');
  });

  it('canonizes camelCase listViews — snake list_views is not a spec key', () => {
    expect(keys).not.toContain('list_views');
  });

  it('does not declare the nine members the retired hand-written interface invented', () => {
    // These were declared by the old mirror, read by nothing in this repo,
    // and absent from the spec document — dropping them followed the spec.
    for (const retired of [
      'extends',
      'triggers',
      'primary_key',
      'relationships',
      'name_field',
      'soft_delete',
      'audit_trail',
      'version',
      'cache',
    ]) {
      expect(keys).not.toContain(retired);
    }
    // The spelling sibling: the identity the old `name_field` member wanted
    // exists in the spec under its camelCase key.
    expect(keys).toContain('nameField');
  });

  it('does not declare the client extension — editMode stays an objectui-side member', () => {
    // If this starts failing, the spec has adopted `editMode`: retire it from
    // `ObjectSchemaClientExtensions` and let the derivation carry it.
    expect(keys).not.toContain('editMode');
  });

  it('accepts the spec-shaped document through the spec parse (value reachability, not just key presence)', () => {
    const { editMode: _clientOnly, ...specShaped } = derivedAdmitsTheThreeKeys;
    const parsed = SpecObjectSchema.safeParse(specShaped);
    expect(parsed.success).toBe(true);
  });

  it('rejects the client extension at the spec parse — editMode is client-side ONLY', () => {
    // The spec parse is strict on unrecognized keys (objectstack#4001), so a
    // published document carrying `editMode` is rejected loudly, not dropped.
    // This pins what "client extension" means: the member exists on the CLIENT
    // type for documents served by client-side data sources, and it cannot
    // ride a spec-validated publish path. If the spec ever adopts `editMode`,
    // this test and the absence test above both flip — retire the extension
    // member and let the derivation carry the key.
    const parsed = SpecObjectSchema.safeParse(derivedAdmitsTheThreeKeys);
    expect(parsed.success).toBe(false);
    if (parsed.success) return;
    const unrecognized = parsed.error.issues.find(
      (issue) => issue.code === 'unrecognized_keys',
    );
    expect(unrecognized).toBeDefined();
    expect(
      (unrecognized as { keys?: string[] } | undefined)?.keys,
    ).toEqual(['editMode']);
  });

  it('keeps the compile-time fixtures alive', () => {
    expect(derivedAdmitsTheThreeKeys.listViews).toBeDefined();
    expect(derivedAdmitsTheThreeKeys.icon).toBe('check-square');
    expect(derivedAdmitsTheThreeKeys.titleFormat).toBe('${subject}');
    expect(snakeSpellingIsNotDeclared.name).toBe('task');
  });
});
