/**
 * ObjectUI
 * Copyright (c) 2024-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * Auto-Layout for ObjectForm
 *
 * Provides intelligent, zero-configuration default layout for metadata-driven forms.
 * When the user has not explicitly set columns/colSpan/sections, this module
 * infers optimal layout based on field count and field types.
 *
 * Priority: User configuration > Auto-layout inference
 */

import type { FormField } from '@object-ui/types';

/** FormField types that are computed/aggregate and must be excluded from modal edit/create forms */
const AUTO_GENERATED_FORM_TYPES = new Set([
  'field:formula',
  'field:summary',
  'field:auto_number',
  'field:autonumber',
  // NOTE: 'field:master_detail' is NOT excluded here. From the child's perspective,
  // a master-detail field is the FK lookup to its parent and is typically required
  // (NOT NULL in the database). It must appear in create/edit forms as a lookup picker.
  // The "embedded sublist on parent detail page" use-case is rendered separately
  // via related-list views, not via the master-detail field type itself.
]);

/** Field types that should span full width in multi-column layouts */
const WIDE_FIELD_TYPES = new Set([
  'field:textarea',
  'field:markdown',
  'field:html',
  'field:grid',
  'field:rich-text',
  'textarea',
  'markdown',
  'html',
  'grid',
  'rich-text',
]);

/**
 * Object field types that are auto-generated/aggregate and should be excluded
 * from modal edit/create forms — they are either computed server-side or render
 * as full-page sub-tables that belong on detail views, not dialogs.
 *
 * NOTE: master_detail/masterDetail are NOT excluded here. From the child-side
 * the field is the FK lookup to the parent (often required / NOT NULL); it must
 * appear in create/edit forms as a lookup picker. The "embedded sublist on the
 * parent's detail page" pattern is rendered by related-list views, not by this
 * field type.
 */
const AUTO_GENERATED_FIELD_TYPES = new Set([
  'formula',
  'summary',
  'auto_number',
  'autonumber',
]);

/**
 * Check if a field type is "wide" (should span full row in multi-column layout).
 */
export function isWideFieldType(type: string): boolean {
  return WIDE_FIELD_TYPES.has(type);
}

/**
 * Check if an object field type is auto-generated (formula, summary, auto_number).
 */
export function isAutoGeneratedFieldType(type: string): boolean {
  return AUTO_GENERATED_FIELD_TYPES.has(type);
}

/**
 * Infer optimal number of columns based on the number of visible fields
 * and whether any wide fields are present.
 *
 * Rules:
 * - 0-3 fields → 1 column
 * - 4+ fields → 2 columns
 */
export function inferColumns(fieldCount: number): number {
  if (fieldCount <= 3) return 1;
  return 2;
}

/**
 * Apply colSpan to wide fields so they span the full row.
 * Only sets colSpan if the field does not already have one explicitly set.
 *
 * @returns A new array of fields with colSpan applied where needed.
 */
export function applyAutoColSpan(fields: FormField[], columns: number): FormField[] {
  if (columns <= 1) return fields;

  return fields.map(field => {
    // User-defined colSpan takes priority
    if (field.colSpan !== undefined) return field;

    // Wide field types should span full row
    if (field.type && isWideFieldType(field.type)) {
      return { ...field, colSpan: columns };
    }

    return field;
  });
}

/**
 * System field names that are always auto-managed by the platform
 * (record identity + audit timestamps) and should never appear on
 * create/edit forms regardless of how they are declared on the schema.
 */
const SYSTEM_FIELD_NAMES = new Set([
  'id',
  'created_at',
  'createdAt',
  'updated_at',
  'updatedAt',
  'last_modified_at',
  'lastModifiedAt',
  'deleted_at',
  'deletedAt',
  'created_by',
  'createdBy',
  'updated_by',
  'updatedBy',
  'last_modified_by',
  'lastModifiedBy',
  'organization_id',
  'organizationId',
  'org_id',
  'orgId',
  'tenant_id',
  'tenantId',
  'owner',
  'owner_id',
  '_version',
  '_rev',
]);

/**
 * Filter out auto-managed system fields (id, audit timestamps, tenant/owner ids).
 * Applied in BOTH create and edit modes, because these fields are always
 * server-populated and rendering them as inputs (even when disabled) just
 * clutters the form. The detail page surfaces the audit metadata via
 * `RecordMetaFooter`.
 */
export function filterSystemFields(
  fields: FormField[],
  objectSchema?: any,
): FormField[] {
  return fields.filter((field) => {
    if (SYSTEM_FIELD_NAMES.has(field.name)) return false;
    const objField = objectSchema?.fields?.[field.name];
    // Honor `hidden: true` — internal/system fields (e.g. database_url,
    // metadata JSON blobs) must never surface as editable inputs in an
    // auto-generated form. The list grid (ObjectGrid) and detail drawer
    // already drop hidden fields; the auto-form is the one place that did
    // not, which leaked e.g. sys_environment.metadata as a raw JSON
    // textarea into the edit dialog. Applied in create AND edit.
    if (objField?.hidden === true) return false;
    // Also drop fields the schema explicitly marks readonly — these are
    // platform-managed (e.g. id alias, formula result columns).
    if (objField?.readonly === true) return false;
    return true;
  });
}

/**
 * Filter out auto-generated/readonly fields for create/edit mode.
 *
 * Dropped:
 * - `formula`, `summary`, `autonumber`, `master_detail` field types (server-computed).
 * - Fields with `readonly: true` on the object schema (e.g. `id`, `created_at`).
 * - Well-known system field names (id, created_at/createdAt, updated_at/updatedAt, etc.),
 *   even when the schema omits `readonly` — these are always platform-managed.
 *
 * Callers can force a readonly field back into the form by marking it
 * `hidden: false, readonly: false` in FormField overrides.
 *
 * @param fields - The form fields array
 * @param objectSchema - The object schema with original field metadata
 * @returns Filtered fields array
 */
export function filterCreateModeFields(
  fields: FormField[],
  objectSchema?: any
): FormField[] {

  return fields.filter(field => {
    // Drop well-known system-managed fields by name (id, created_at, updated_at, …).
    if (SYSTEM_FIELD_NAMES.has(field.name)) return false;

    // Check FormField.type directly (mapped type like 'field:formula')
    if (field.type && AUTO_GENERATED_FORM_TYPES.has(field.type)) return false;

    // Check against object schema field type + readonly flag
    if (!objectSchema?.fields) return true;
    const objField = objectSchema.fields[field.name];
    if (!objField) return true; // keep fields not in schema (custom fields)

    // Drop fields the schema declares as readonly — they are auto-managed.
    if (objField.readonly === true) return false;

    return !isAutoGeneratedFieldType(objField.type);
  });
}

/**
 * Filter auto-generated computed fields (formula, summary, etc.) — applied in
 * CREATE mode only. In edit mode these fields remain visible so users can see
 * their current computed values rendered as readonly.
 */
export function filterAutoGeneratedFields(
  fields: FormField[],
  objectSchema?: any,
): FormField[] {
  return fields.filter((field) => {
    if (field.type && AUTO_GENERATED_FORM_TYPES.has(field.type)) return false;
    const objField = objectSchema?.fields?.[field.name];
    if (!objField) return true;
    return !isAutoGeneratedFieldType(objField.type);
  });
}

/**
 * Infer an appropriate modal size based on the number of layout columns.
 * Used to auto-upgrade the modal width when auto-layout detects multi-column forms.
 *
 * Mapping:
 * - 1 column   → 'default' (max-w-lg)
 * - 2 columns  → 'xl'      (max-w-5xl)
 * - 3+ columns → 'full'    (max-w-[95vw])
 */
export function inferModalSize(columns: number): 'sm' | 'default' | 'lg' | 'xl' | 'full' {
  if (columns <= 1) return 'default';
  if (columns === 2) return 'xl';
  return 'full';
}

/**
 * Main auto-layout orchestrator.
 * Applies intelligent defaults only when the user has not explicitly configured layout.
 *
 * @param formFields - Generated form fields
 * @param objectSchema - The original object schema (with field types)
 * @param schemaColumns - User-provided columns (from ObjectFormSchema)
 * @param mode - Form mode ('create' | 'edit' | 'view')
 * @returns Object with processed fields and inferred columns
 */
export function applyAutoLayout(
  formFields: FormField[],
  objectSchema: any,
  schemaColumns: number | undefined,
  mode: string | undefined
): { fields: FormField[]; columns: number | undefined } {
  let fields = [...formFields];

  // Step 1a: Always drop platform-managed system fields (id, audit timestamps,
  // tenant ids, etc.) from create AND edit forms. They're populated by the
  // driver/security plugin, and the detail page surfaces audit metadata via
  // RecordMetaFooter — so showing them as (disabled) inputs is pure clutter.
  fields = filterSystemFields(fields, objectSchema);

  // Step 1b: In create mode, additionally drop formula/summary/auto-number
  // fields (server-computed). In edit mode keep them so users can see their
  // current computed values, typically rendered as readonly.
  if (mode === 'create') {
    fields = filterAutoGeneratedFields(fields, objectSchema);
  }

  // Step 2: If user explicitly set columns, respect it but still apply auto colSpan
  if (schemaColumns !== undefined) {
    fields = applyAutoColSpan(fields, schemaColumns);
    return { fields, columns: schemaColumns };
  }

  // Step 3: Infer columns from field count
  const columns = inferColumns(fields.length);

  // Step 4: Apply auto colSpan for wide fields
  fields = applyAutoColSpan(fields, columns);

  return { fields, columns };
}
