/**
 * ObjectUI
 * Copyright (c) 2024-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useContext } from 'react';
import { ComponentRegistry } from '@object-ui/core';
import {
  ElementDataSourceGate,
  SchemaRendererContext,
  type ElementDataSourceMapping,
} from '@object-ui/react';
import { ObjectForm } from './ObjectForm';

export { ObjectForm };
export type { ObjectFormProps } from './ObjectForm';
export { FormSectionContainer } from './FormSection';
export type { FormSectionContainerProps } from './FormSection';
export {
  applyAutoLayout,
  inferColumns,
  inferModalSize,
  isWideFieldType,
  isAutoGeneratedFieldType,
  applyAutoColSpan,
  containerGridColsFor,
  filterCreateModeFields,
  filterSystemFields,
  filterAutoGeneratedFields,
} from './autoLayout';
export { TabbedForm } from './TabbedForm';
export type { TabbedFormProps, TabbedFormSchema, FormSectionConfig } from './TabbedForm';
export { WizardForm } from './WizardForm';
export type { WizardFormProps, WizardFormSchema } from './WizardForm';
export { SplitForm } from './SplitForm';
export type { SplitFormProps, SplitFormSchema } from './SplitForm';
export { DrawerForm } from './DrawerForm';
export type { DrawerFormProps, DrawerFormSchema } from './DrawerForm';
export { ModalForm } from './ModalForm';
export type { ModalFormProps, ModalFormSchema } from './ModalForm';
export { EmbeddableForm } from './EmbeddableForm';
export type { EmbeddableFormProps, EmbeddableFormConfig, EmbeddableFormTexts } from './EmbeddableForm';
export { FormAnalytics } from './FormAnalytics';
export type { FormAnalyticsProps, FormSubmissionMetric } from './FormAnalytics';
export { MasterDetailForm } from './MasterDetailForm';
export type {
  MasterDetailFormProps,
  MasterDetailFormSchema,
  MasterDetailDetailConfig,
} from './MasterDetailForm';
export { LineItemsPanel } from './LineItemsPanel';
export type { LineItemsPanelSchema } from './LineItemsPanel';
export { deriveDetail, deriveColumns, deriveFormFields, findRelationshipField, resolveInlineMode } from './deriveMasterDetail';
export type { DerivedDetail, InlineMode } from './deriveMasterDetail';

// Register object-form component
const ObjectFormRenderer: React.FC<{ schema: any }> = ({ schema }) => {
  // Resolve dataSource from the SchemaRendererProvider context (same as
  // object-view): ObjectForm needs a dataSource to fetch the object schema and
  // auto-generate its fields. Without this, an `object-form` rendered straight
  // through SchemaRenderer (e.g. the Studio view preview) has no fields.
  const ctx = useContext(SchemaRendererContext as React.Context<any>);
  const dataSource = ctx?.dataSource ?? undefined;
  // The spec's `PageComponentSchema.dataSource` binding (objectstack#6953). A
  // page that declared `dataSource: { object }` and no `objectName` rendered a
  // field-less shell: `ObjectForm` gates its whole schema fetch on `objectName`.
  //
  // `object` is the ONLY key of the binding this block can honour, and the
  // mapping says so rather than parking the rest somewhere plausible. A form
  // edits ONE record — it has no collection query, so there is nothing for
  // `filter` / `sort` / `limit` to narrow, and a saved LIST view's columns are
  // not a form layout (`fields` here is an ordered layout, not a projection).
  // A `view` name is still resolved, so naming one that does not exist reports
  // instead of rendering; a view that DOES resolve contributes nothing on this
  // block, which is recorded as the residual gap on objectstack#6953.
  return (
    <ElementDataSourceGate
      schema={schema}
      dataSource={dataSource}
      testId="object-form"
      errorTitle="This form’s data source could not be resolved"
    >
      {(bound) => <ObjectForm schema={bound} dataSource={dataSource} />}
    </ElementDataSourceGate>
  );
};

ComponentRegistry.register('object-form', ObjectFormRenderer, {
  namespace: 'plugin-form',
  label: 'Object Form',
  category: 'plugin',
  inputs: [
    { name: 'objectName', type: 'string', label: 'Object Name', required: true },
    { name: 'fields', type: 'array', label: 'Fields' },
    { name: 'mode', type: 'enum', label: 'Mode', enum: ['create', 'edit', 'view'] },
    { name: 'formType', type: 'enum', label: 'Form Type', enum: ['simple', 'tabbed', 'wizard', 'split', 'drawer', 'modal'] },
    { name: 'sections', type: 'array', label: 'Sections' },
    { name: 'title', type: 'string', label: 'Title' },
    { name: 'description', type: 'string', label: 'Description' },
    { name: 'layout', type: 'enum', label: 'Layout', enum: ['vertical', 'horizontal', 'inline', 'grid'] },
    { name: 'columns', type: 'number', label: 'Columns' },
    // Tabbed
    { name: 'defaultTab', type: 'string', label: 'Default Tab' },
    { name: 'tabPosition', type: 'enum', label: 'Tab Position', enum: ['top', 'bottom', 'left', 'right'] },
    // Wizard
    { name: 'allowSkip', type: 'boolean', label: 'Allow Skip Steps' },
    { name: 'showStepIndicator', type: 'boolean', label: 'Show Step Indicator' },
    // Split
    { name: 'splitDirection', type: 'enum', label: 'Split Direction', enum: ['horizontal', 'vertical'] },
    { name: 'splitSize', type: 'number', label: 'Split Panel Size (%)' },
    { name: 'splitResizable', type: 'boolean', label: 'Split Resizable' },
    // Drawer
    { name: 'drawerSide', type: 'enum', label: 'Drawer Side', enum: ['top', 'bottom', 'left', 'right'] },
    { name: 'drawerWidth', type: 'string', label: 'Drawer Width' },
    // Modal
    { name: 'modalSize', type: 'enum', label: 'Modal Size', enum: ['sm', 'default', 'lg', 'xl', 'full'] },
  ]
});

// Register as view:form for the standard view protocol
// This allows using { type: 'view:form', objectName: '...' } in schemas
// skipFallback prevents overwriting the basic 'form' component from @object-ui/components
ComponentRegistry.register('form', ObjectFormRenderer, {
  namespace: 'view',
  skipFallback: true,
  label: 'Data Form View',
  category: 'view',
  inputs: [
    { name: 'objectName', type: 'string', label: 'Object Name', required: true },
    { name: 'fields', type: 'array', label: 'Fields' },
    { name: 'mode', type: 'enum', label: 'Mode', enum: ['create', 'edit', 'view'] },
  ]
});

// Note: 'form' type (without namespace) is handled by @object-ui/components Form component
// This plugin registers as 'view:form' (with view namespace) for the view protocol
// ObjectForm internally uses { type: 'form' } to render the basic Form component

// Register embeddable-form component for standalone public forms
import { EmbeddableForm } from './EmbeddableForm';

const EmbeddableFormRenderer: React.FC<{ schema: any }> = ({ schema }) => {
  // Same bridge `object-form` above does, and for the same reason (#3144):
  // `EmbeddableForm` needs a dataSource to fetch the object schema — its own
  // comment says so — and `SchemaRenderer` only ever puts one on the context,
  // never on props. Dropping it here meant an `embeddable-form` rendered
  // through the registry declared `objectName` **required** and then had
  // nothing to bind it to, rendering a field-less shell. That is the
  // objectstack#4413 shape; `public-block-binding-reach.test.tsx` is what
  // catches it now.
  const ctx = useContext(SchemaRendererContext as React.Context<any>);
  // The spec's `PageComponentSchema.dataSource` binding (objectstack#7121). Same
  // standing, and the same single mapped key, as `object-form` above:
  // `EmbeddableForm` reads `config.objectName` to fetch the object's fields and
  // to `create()` the submission, so a form authored with `dataSource: { object }`
  // and no flat `objectName` rendered a field-less shell that could not submit.
  //
  // `filter` / `sort` / `limit` have no read site on a form that CREATES one
  // record — there is no collection query for them to narrow — and `fields` is an
  // ordered layout, not a projection a list view's columns could fill, so none of
  // them is mapped. A `view` name is still resolved (a typo reports rather than
  // rendering), and a view that does resolve contributes nothing here.
  return (
    <ElementDataSourceGate
      schema={schema}
      dataSource={ctx?.dataSource}
      testId="embeddable-form"
      errorTitle="This form’s data source could not be resolved"
    >
      {(bound) => <EmbeddableForm config={bound} dataSource={ctx?.dataSource} />}
    </ElementDataSourceGate>
  );
};

ComponentRegistry.register('embeddable-form', EmbeddableFormRenderer, {
  namespace: 'plugin-form',
  label: 'Embeddable Form',
  category: 'plugin',
  inputs: [
    { name: 'formId', type: 'string', label: 'Form ID', required: true },
    { name: 'objectName', type: 'string', label: 'Object Name', required: true },
    { name: 'title', type: 'string', label: 'Form Title' },
    { name: 'description', type: 'string', label: 'Description' },
    { name: 'fields', type: 'array', label: 'Fields' },
    { name: 'allowMultiple', type: 'boolean', label: 'Allow Multiple Submissions' },
  ]
});

// Register form-analytics component for submission dashboards
import { FormAnalytics } from './FormAnalytics';

const FormAnalyticsRenderer: React.FC<{ schema: any }> = ({ schema }) => {
  return <FormAnalytics formId={schema.formId} formTitle={schema.formTitle} metrics={schema.metrics || { totalSubmissions: 0 }} />;
};

ComponentRegistry.register('form-analytics', FormAnalyticsRenderer, {
  namespace: 'plugin-form',
  label: 'Form Analytics',
  category: 'plugin',
  inputs: [
    { name: 'formId', type: 'string', label: 'Form ID', required: true },
    { name: 'formTitle', type: 'string', label: 'Form Title' },
    { name: 'metrics', type: 'object', label: 'Submission Metrics' },
  ]
});

// Register master-detail composite form (parent + child line items, entered
// together — see ADR-0001).
import { MasterDetailForm } from './MasterDetailForm';

const MasterDetailFormRenderer: React.FC<{ schema: any }> = ({ schema }) => {
  const ctx = useContext(SchemaRendererContext as React.Context<any>);
  const dataSource = ctx?.dataSource ?? undefined;
  // The spec's `PageComponentSchema.dataSource` binding (objectstack#7121).
  // `schema.objectName` is the PARENT object here, and everything downstream is
  // gated on it — `deriveDetail` needs it to find each child's relationship field
  // back to the parent, and the parent form/save path names it directly. A
  // master-detail form authored with `dataSource: { object }` and no flat
  // `objectName` therefore rendered a parent shell whose details could not even
  // resolve their own FK.
  //
  // `object` is the only key mapped, and for the same reason as the two forms
  // above: the parent is ONE record (no collection query for `filter` / `sort` /
  // `limit` to narrow) and the child collections are fetched by FK from
  // `schema.details`, at a fixed `$top: 500`, not from anything the binding
  // carries. `details[].columns` is a per-child editable grid spec, not a
  // projection a saved view could supply.
  return (
    <ElementDataSourceGate
      schema={schema}
      dataSource={dataSource}
      testId="object-master-detail-form"
      errorTitle="This form’s data source could not be resolved"
    >
      {(bound) => <MasterDetailForm schema={bound} dataSource={dataSource} />}
    </ElementDataSourceGate>
  );
};

ComponentRegistry.register('object-master-detail-form', MasterDetailFormRenderer, {
  namespace: 'plugin-form',
  label: 'Master-Detail Form',
  category: 'plugin',
  inputs: [
    { name: 'objectName', type: 'string', label: 'Parent Object', required: true },
    { name: 'mode', type: 'enum', label: 'Mode', enum: ['create', 'edit'] },
    { name: 'sections', type: 'array', label: 'Parent Sections' },
    { name: 'details', type: 'array', label: 'Detail Collections', required: true },
  ],
});

// Register record:line_items — child grid bound to an existing parent record,
// usable on a record/detail page or slotted slot.
import { LineItemsPanel } from './LineItemsPanel';

/**
 * `record:line_items` is the one block in this batch whose object does NOT live
 * under `objectName`: the collection it lists, fetches and writes is
 * `schema.childObject` (`LineItemsPanel.tsx` — `dataSource.find(schema.childObject,
 * …)`, `getObjectSchema(schema.childObject)`, and the child leg of the save
 * batch). So the binding's `object` maps THERE, the same way it maps onto
 * `record:related_list`'s `objectName` — in both blocks that key names the CHILD
 * object the panel is bound to, which is what `dataSource.object` means.
 *
 * Nothing else is mapped, and each omission has a read site behind it (or the
 * lack of one):
 *
 *  - `relationshipField` stays the author's: it is not part of the binding, and it
 *    must name a field ON the bound child object. Rebinding `object` without
 *    updating it is an authoring error the panel cannot paper over.
 *  - `filter` has no read site — the query is `{ [relationshipField]: parentId }`
 *    and nothing else, so the panel is scoped by the parent record alone.
 *  - `sort` and a row cap likewise: rows come back at a fixed `$top: 500` in
 *    storage order.
 *  - `columns` is NOT a field-name projection here. It is `GridColumn[]`
 *    (`{ field, type, options, computed, expr, … }`) driving an EDITABLE grid; a
 *    saved view's column list would arrive as bare names and render a grid of
 *    column definitions with no `field`. Wrong shape, not merely a wider answer.
 *
 * Consequence, stated rather than hidden: a `view` named on this block is
 * resolved (so a typo reports instead of silently widening) and then contributes
 * nothing — its filter/sort/columns are all dropped, because the panel has no
 * read site for any of them.
 */
const RECORD_LINE_ITEMS_DATA_SOURCE: ElementDataSourceMapping = {
  object: 'childObject',
};

const LineItemsPanelRenderer: React.FC<{ schema: any }> = ({ schema }) => (
  // The spec's `PageComponentSchema.dataSource` binding (objectstack#7121). No
  // `dataSource` is passed: the gate falls back to `SchemaRendererContext`, which
  // is the very adapter `LineItemsPanel` loads its rows through — resolving `view`
  // against a different source than the rows come from could report a view as
  // missing on a host that has it.
  <ElementDataSourceGate
    schema={schema}
    mapping={RECORD_LINE_ITEMS_DATA_SOURCE}
    testId="record-line-items"
    errorTitle="This line-items panel’s data source could not be resolved"
  >
    {(bound) => <LineItemsPanel schema={bound} />}
  </ElementDataSourceGate>
);

ComponentRegistry.register('line_items', LineItemsPanelRenderer, {
  namespace: 'record',
  skipFallback: true,
  label: 'Line Items',
  category: 'record',
  inputs: [
    { name: 'childObject', type: 'string', label: 'Child Object', required: true },
    { name: 'relationshipField', type: 'string', label: 'Relationship Field', required: true },
    { name: 'columns', type: 'array', label: 'Columns', required: true },
    { name: 'totalField', type: 'string', label: 'Parent Total Field' },
    { name: 'amountField', type: 'string', label: 'Amount Column' },
  ],
});
